//! LLVM backend (migration plan `docs/llvm-backend-plan.md`, M1
//! skeleton). Emits a textual LLVM IR module that `clang` compiles and
//! links against `libklassic_runtime.a`. This first milestone proves the
//! pipeline `.kl -> LLVM IR -> clang -> executable`; it lowers only a
//! program made of top-level `println(<integer expression>)` statements
//! (integer literals and `+ - * /`). Anything outside that subset fails
//! with a source-located diagnostic — never wrong code. Coverage grows
//! milestone by milestone (M3 onward); the hand-emitted backend stays the
//! default and untouched.

use klassic_span::{Diagnostic, Span};
use klassic_syntax::{BinaryOp, Expr};

fn unsupported(span: Span, feature: &str) -> Diagnostic {
    Diagnostic::compile(
        span,
        format!("{feature} is not supported by the LLVM backend yet"),
    )
}

#[derive(Default)]
struct LlvmEmitter {
    body: String,
    next_temp: u32,
}

impl LlvmEmitter {
    fn fresh(&mut self) -> String {
        let temp = format!("%t{}", self.next_temp);
        self.next_temp += 1;
        temp
    }

    /// Lower an integer expression to IR, returning an operand string
    /// (an immediate like `42` or an SSA temporary like `%t3`).
    fn int_expr(&mut self, expr: &Expr) -> Result<String, Diagnostic> {
        match expr {
            Expr::Int { value, .. } => Ok(value.to_string()),
            Expr::Binary { lhs, op, rhs, span } => {
                let left = self.int_expr(lhs)?;
                let right = self.int_expr(rhs)?;
                let instr = match op {
                    BinaryOp::Add => "add",
                    BinaryOp::Subtract => "sub",
                    BinaryOp::Multiply => "mul",
                    BinaryOp::Divide => "sdiv",
                    _ => return Err(unsupported(*span, "this operator")),
                };
                let temp = self.fresh();
                self.body
                    .push_str(&format!("  {temp} = {instr} i64 {left}, {right}\n"));
                Ok(temp)
            }
            other => Err(unsupported(other.span(), "expression")),
        }
    }
}

fn is_println(callee: &Expr) -> bool {
    matches!(callee, Expr::Identifier { name, .. } if name == "println")
}

/// Emit the whole program as an LLVM IR module. The program must be a
/// sequence of top-level `println(<integer expression>)` calls.
pub(crate) fn emit_llvm_program(expr: &Expr) -> Result<String, Diagnostic> {
    let statements: Vec<&Expr> = match expr {
        Expr::Block { expressions, .. } => expressions.iter().collect(),
        other => vec![other],
    };

    let mut emitter = LlvmEmitter::default();
    for statement in statements {
        match statement {
            Expr::Call {
                callee,
                arguments,
                span,
            } if is_println(callee) => {
                if arguments.len() != 1 {
                    return Err(unsupported(*span, "println with other than 1 argument"));
                }
                let operand = emitter.int_expr(&arguments[0])?;
                emitter.body.push_str(&format!(
                    "  call void @klassic_rt_println_i64(i64 {operand})\n"
                ));
            }
            other => {
                return Err(unsupported(
                    other.span(),
                    "top-level statement (the LLVM backend currently handles only \
                     println of an integer expression)",
                ));
            }
        }
    }

    let mut out = String::new();
    out.push_str("; generated by klassic --backend llvm (M1 skeleton)\n");
    out.push_str("target triple = \"x86_64-pc-linux-gnu\"\n\n");
    out.push_str("declare void @klassic_rt_println_i64(i64)\n\n");
    out.push_str("define i32 @main() {\nentry:\n");
    out.push_str(&emitter.body);
    out.push_str("  ret i32 0\n}\n");
    Ok(out)
}

#[cfg(test)]
mod tests {
    use crate::compile_source_to_llvm;

    #[test]
    fn println_of_an_integer_literal_lowers_to_a_runtime_call() {
        let ir = compile_source_to_llvm("t", "println(42)\n").expect("should compile");
        assert!(ir.contains("declare void @klassic_rt_println_i64(i64)"));
        assert!(ir.contains("define i32 @main()"));
        assert!(ir.contains("call void @klassic_rt_println_i64(i64 42)"));
        assert!(ir.contains("ret i32 0"));
    }

    #[test]
    fn integer_arithmetic_lowers_with_precedence() {
        // 1 + 2 * 3 must multiply first, then add — a single mul feeding
        // an add, printed as 7 (matches the evaluator).
        let ir = compile_source_to_llvm("t", "println(1 + 2 * 3)\n").expect("should compile");
        assert!(ir.contains("mul i64 2, 3"), "IR was:\n{ir}");
        assert!(ir.contains("add i64 1, %t0"), "IR was:\n{ir}");
    }

    #[test]
    fn unsupported_construct_fails_cleanly() {
        // The M1 skeleton handles only println of integer expressions;
        // anything else is a source-located diagnostic, never wrong code.
        let err = compile_source_to_llvm("t", "val x = 1\nprintln(x)\n");
        assert!(err.is_err(), "non-subset program must be rejected");
    }
}
